import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { BIN } from '../config.mjs';

const exec = promisify(execFile);

/**
 * Codex CLI adapter.
 *
 * `codex exec --json` emits structured JSONL, so this adapter is as faithful as
 * the Claude one — no heuristics over terminal text. The vocabulary:
 *
 *   thread.started    start, carries the thread_id (session id)
 *   turn.started      turn start
 *   item.started      an item began (command, file edit)
 *   item.completed    item finished; its `type` says what it was
 *   turn.completed    end, with token usage
 *
 * And the item types that matter: `agent_message` (text), `command_execution`
 * (shell, with command/output/exit_code), `file_change` (paths and kind of
 * change), `reasoning` and `error`.
 *
 * The relevant difference from the other tools: Codex reports usage in TOKENS,
 * not in cost. Converting to money would need a per-model price table that would
 * silently go stale — so `cost` stays null and the tokens travel in the result
 * event, honest about what they are.
 */

const CODEX_HOME = process.env.CODEX_HOME || path.join(os.homedir(), '.codex');

/**
 * Mode-to-sandbox mapping.
 *
 * Codex does not separate "read only" from "read and execute": under `read-only`
 * the model's commands still run, they just cannot write. So `ro` and `verify`
 * land on the same sandbox, and `ro` ends up more permissive here than on the
 * other tools. We prefer that over promising isolation the binary does not
 * deliver.
 */
const SANDBOX = {
  ro: 'read-only',
  verify: 'read-only',
  rw: 'workspace-write',
  full: 'danger-full-access',
};

// known noise from Codex itself, not from the task
const BENIGN = [
  /Skill descriptions were shortened/i,
  /failed to load skill/i,
  /worker quit with fatal/i,
  /Reading additional input from stdin/i,
];

export const codex = {
  name: 'codex',
  displayName: 'Codex CLI',
  capabilities: {
    structuredEvents: true,
    liveSessions: false,
    resume: true,
    // the thread_id is generated by Codex; we capture it to resume, but we
    // cannot impose an id of our own up front
    controlledSessionId: false,
    cost: false,
    tokens: true,
  },

  async available() {
    try {
      await exec(BIN.codex, ['--version'], { timeout: 15000 });
      return true;
    } catch {
      return false;
    }
  },

  /**
   * Sessions recorded on disk. Includes the desktop app's, which writes to the
   * same place — that is why `origin` shows up in the listing.
   */
  async listSessions({ cwd, limit = 40 } = {}) {
    const root = path.join(CODEX_HOME, 'sessions');
    if (!fs.existsSync(root)) return [];

    const files = [];
    const walk = (dir, depth = 0) => {
      if (depth > 4 || files.length > 400) return;
      let entries;
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch {
        return;
      }
      for (const e of entries) {
        const full = path.join(dir, e.name);
        if (e.isDirectory()) walk(full, depth + 1);
        else if (e.name.endsWith('.jsonl')) files.push(full);
      }
    };
    walk(root);

    // newest first, by name (rollout-<ISO>-<id>.jsonl sorts well)
    files.sort().reverse();

    const sessions = [];
    for (const file of files.slice(0, 200)) {
      if (sessions.length >= limit) break;
      let meta;
      try {
        const firstLine = fs.readFileSync(file, 'utf8').split('\n', 1)[0];
        const parsed = JSON.parse(firstLine);
        if (parsed.type !== 'session_meta') continue;
        meta = parsed.payload;
      } catch {
        continue;
      }
      if (!meta?.session_id) continue;
      if (cwd && meta.cwd && meta.cwd !== cwd) continue;

      sessions.push({
        tool: 'codex',
        id: meta.session_id,
        name: meta.cwd ? path.basename(meta.cwd) : meta.session_id.slice(0, 8),
        cwd: meta.cwd || null,
        status: 'saved',
        origin: meta.originator || null,
        startedAt: meta.timestamp ? Date.parse(meta.timestamp) : null,
      });
    }

    return sessions;
  },

  run({ prompt, cwd, sessionId, resume, mode = 'ro', model, mcpServers, env, onEvent, timeoutMs }) {
    const sandbox = SANDBOX[mode] || SANDBOX.ro;
    const resuming = !!(resume && sessionId);

    /**
     * `codex exec` and `codex exec resume` do not accept the same set of flags:
     * resume has no `--sandbox` and no `-C`. That means on resume the sandbox is
     * inherited from the original session and the directory comes from the
     * process cwd — which is why the spawn below always sets `cwd` instead of
     * relying on `-C`.
     *
     * Practical consequence: resuming a session created in a permissive mode does
     * not become restricted just because we asked for `ro` now. Anyone who needs
     * guaranteed isolation should start a new run, not continue an old one.
     */
    const args = ['exec'];
    if (resuming) args.push('resume');
    args.push('--json', '--skip-git-repo-check');
    if (model) args.push('--model', model);
    if (!resuming) args.push('--sandbox', sandbox, '-C', cwd);

    /**
     * Codex has no `--mcp-config`; it takes config overrides whose value is
     * parsed as TOML, which is enough to declare a server inline. Written as
     * separate `-c` pairs because a single nested table override is not accepted.
     */
    for (const [name, cfg] of Object.entries(mcpServers || {})) {
      args.push('-c', `mcp_servers.${name}.command=${JSON.stringify(cfg.command)}`);
      if (cfg.args?.length) {
        args.push('-c', `mcp_servers.${name}.args=${JSON.stringify(cfg.args)}`);
      }
    }

    if (resuming) args.push(sessionId);
    args.push(prompt);

    const child = spawn(BIN.codex, args, {
      cwd,
      // stdin closed: with stdin open Codex sits waiting for extra input
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, ...(env || {}), NO_COLOR: '1' },
    });

    let sid = sessionId || null;
    let finalText = '';
    let usage = null;
    let buf = '';
    const stderr = [];

    const handleLine = (line) => {
      if (!line.trim()) return;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch {
        if (!BENIGN.some((re) => re.test(line))) {
          onEvent({ type: 'log', tool: 'codex', text: line });
        }
        return;
      }

      switch (msg.type) {
        case 'thread.started':
          sid = msg.thread_id || sid;
          onEvent({ type: 'status', tool: 'codex', status: 'running', sessionId: sid });
          break;

        case 'item.started':
        case 'item.completed': {
          const item = msg.item || {};
          const done = msg.type === 'item.completed';

          switch (item.type) {
            case 'agent_message':
              if (done && item.text) {
                finalText = item.text;
                onEvent({ type: 'text', tool: 'codex', delta: false, text: item.text + '\n' });
              }
              break;

            case 'reasoning':
              if (done && item.text) {
                onEvent({ type: 'thinking', tool: 'codex', delta: false, text: item.text });
              }
              break;

            case 'command_execution':
              if (!done) {
                onEvent({
                  type: 'tool_use',
                  tool: 'codex',
                  toolName: 'shell',
                  toolUseId: item.id,
                  input: { command: item.command },
                });
              } else {
                onEvent({
                  type: 'tool_result',
                  tool: 'codex',
                  toolUseId: item.id,
                  isError: item.exit_code !== 0,
                  text: (item.aggregated_output || '').slice(0, 8000),
                });
              }
              break;

            case 'file_change':
              if (done) {
                const paths = (item.changes || []).map((c) => `${c.kind}: ${c.path}`);
                onEvent({
                  type: 'tool_use',
                  tool: 'codex',
                  toolName: 'edit',
                  toolUseId: item.id,
                  input: { summary: paths.join(', ') },
                });
              }
              break;

            case 'error':
              // Codex's own warnings about skills/MCP are not a task failure
              if (done && item.message && !BENIGN.some((re) => re.test(item.message))) {
                onEvent({ type: 'error', tool: 'codex', text: item.message });
              }
              break;
          }
          break;
        }

        case 'turn.completed':
          usage = msg.usage || null;
          break;

        case 'turn.failed':
          onEvent({
            type: 'error',
            tool: 'codex',
            text: msg.error?.message || 'turno falhou',
          });
          break;
      }
    };

    child.stdout.on('data', (chunk) => {
      buf += chunk.toString();
      const lines = buf.split('\n');
      buf = lines.pop();
      for (const l of lines) handleLine(l);
    });

    child.stderr.on('data', (chunk) => {
      const text = chunk.toString();
      stderr.push(text);
      for (const line of text.split('\n')) {
        if (line.trim() && !BENIGN.some((re) => re.test(line))) {
          onEvent({ type: 'log', tool: 'codex', stream: 'stderr', text: line });
        }
      }
    });

    const done = new Promise((resolve) => {
      let timer = null;
      if (timeoutMs) {
        timer = setTimeout(() => {
          onEvent({ type: 'error', tool: 'codex', text: `timeout apos ${timeoutMs}ms` });
          child.kill('SIGTERM');
          setTimeout(() => child.kill('SIGKILL'), 5000);
        }, timeoutMs);
      }

      child.on('close', (code, signal) => {
        if (timer) clearTimeout(timer);
        if (buf.trim()) handleLine(buf);

        const totalTokens = usage
          ? (usage.input_tokens || 0) + (usage.output_tokens || 0)
          : null;

        onEvent({
          type: 'result',
          tool: 'codex',
          text: finalText,
          isError: code !== 0,
          cost: null,
          tokens: totalTokens,
          usage,
          sessionId: sid,
        });

        resolve({
          ok: code === 0,
          code,
          signal,
          sessionId: sid,
          output: finalText,
          cost: null,
          tokens: totalTokens,
          usage,
          stderr: stderr.join('').slice(-4000),
        });
      });

      child.on('error', (err) => {
        if (timer) clearTimeout(timer);
        onEvent({ type: 'error', tool: 'codex', text: err.message });
        resolve({ ok: false, code: -1, sessionId: sid, output: '', error: err.message });
      });
    });

    return { child, sessionId: sid, done };
  },
};
